move ddUrl to portal config
uc-cdis/data-portal pull request #1410
Opened 2023-09-13 18:24 UTC by jawadqur

### New Features

### Breaking Changes

### Bug Fixes

### Improvements
- Move ddUrl for RUM to configuration, instead of hardcoding - This is necessary for the move to datadog govcloud. 

### Dependency updates

### Deployment changes

2023-09-13 21:39 UTC, mfshao approved these changes

2023-09-14 14:30 UTC, ocshawn requested changes
please update the documentation with this new variable and a description of what it does. Docs can be found at https://github.com/uc-cdis/data-portal/tree/master/docs

2023-09-14 14:35 UTC, jawadqur commented
> please update the documentation with this new variable and a description of what it does. Docs can be found at https://github.com/uc-cdis/data-portal/tree/master/docs

Good call! Added documentation

2023-09-14 16:05 UTC, ocshawn approved these changes

2023-09-14 16:34 UTC, merged