(VADC-1439): add link to access denied page
uc-cdis/data-portal pull request #1616
Opened 2024-10-25 21:01 UTC by ocshawn

Link to JIRA ticket if there is one: [VADC-1439](https://ctds-planx.atlassian.net/browse/VADC-1439)

### New Features
- add link to access denied page

2024-10-30 15:05 UTC, craigrbarnes approved these changes

2024-10-30 18:45 UTC, cemile-ctds requested changes
Please change the title and description to the text below:
ACCESS DENIED
You are not authorized to access this system. If you have any questions, please log out and contact vadc@lists.uchicago.edu

[button] Logout and Return to Homepage
![Screenshot 2024-10-29 at 17 08 40](https://github.com/user-attachments/assets/59bb124f-42d8-4cc8-81a5-e7d78c03a3dd)

2024-10-31 16:25 UTC, cemile-ctds approved these changes
Looks good on my side.

2024-11-14 16:11 UTC, mfshao approved these changes

2024-11-14 21:55 UTC, merged