ARIA dialog and alertdialog nodes should have an accessible name
uc-cdis/data-portal pull request #1642
Opened 2024-11-19 18:07 UTC by tianj7

https://ctds-planx.atlassian.net/browse/VADC-1419

### Improvements
Add aria label for popup message

2024-11-19 21:26 UTC, ocshawn reviewed
unsure what this is accomplishing as it looks like you are adding a pointer that points to itself

2024-11-20 00:11 UTC, tianj7 commented
> unsure what this is accomplishing as it looks like you are adding a pointer that points to itself

Updated code

2024-11-20 14:52 UTC, jarvisraymond-uchicago requested changes

2024-11-20 14:52 UTC, jarvisraymond-uchicago commented on src/components/Popup.jsx
> +                      aria-labelledby='popup__message'
@tianj7 could you please touch base with @cemile-ctds regarding the business requirements? Usually the aria-labelledby acts by referencing the id of another element that provides the label text for screen readers. I believe if we have aria-labelledby we would not need the aria-labels you have added. Also make sure the element with the id `popup_message` is the correct element to act as the label.

2024-11-20 18:04 UTC, closed without merging